### ISSUE TITLE
Delphi 11 compilation warnings

### ISSUE THREAD

**Issue by piotrx** [exilon/QuickLogger#65] opened 2021-12-21 12:33 UTC
Hi,

QuickLogger installed from GetIt during compilation on Delphi 11 has this kind of warnings:

[dcc32 Warning] Quick.JSON.Utils.pas(102): W1050 WideChar reduced to byte char in set expressions.  Consider using 'CharInSet' function in 'SysUtils' unit.
[dcc32 Warning] Quick.JSON.Utils.pas(116): W1050 WideChar reduced to byte char in set expressions.  Consider using 'CharInSet' function in 'SysUtils' unit.
[dcc32 Warning] Quick.Json.Serializer.pas(466): W1035 Return value of function 'TRTTIJson.DeserializeStream' might be undefined
[dcc32 Warning] Quick.Json.Serializer.pas(590): W1057 Implicit string cast from 'TSymbolName' to 'string'
[dcc32 Warning] Quick.Json.Serializer.pas(1301): W1057 Implicit string cast from 'TSymbolName' to 'string'
[dcc32 Hint] Quick.Json.Serializer.pas(1456): H2164 Variable 'json' is declared but never used in 'TRTTIJson.SerializeStream'
[dcc32 Hint] Quick.Json.Serializer.pas(134): H2219 Private symbol 'GetValue' declared but never used
[dcc32 Hint] Quick.Json.Serializer.pas(136): H2219 Private symbol 'GetPropertyValue' declared but never used
[dcc32 Hint] Quick.Json.Serializer.pas(142): H2219 Private symbol 'SetPropertyValue' declared but never used
[dcc32 Hint] Quick.Json.Serializer.pas(205): H2219 Private symbol 'SetUseNullStringsAsEmpty' declared but never used
[dcc32 Warning] Quick.Threads.pas(2444): W1035 Return value of function 'TBackgroundWorkers.WaitAndRetry' might be undefined
[dcc32 Warning] Quick.Threads.pas(2449): W1035 Return value of function 'TBackgroundWorkers.WaitAndRetry' might be undefined
[dcc32 Warning] Quick.Threads.pas(2454): W1035 Return value of function 'TBackgroundWorkers.WaitAndRetry' might be undefined
[dcc32 Warning] Quick.Threads.pas(2459): W1035 Return value of function 'TBackgroundWorkers.WaitAndRetryForever' might be undefined
[dcc32 Warning] Quick.Threads.pas(2464): W1035 Return value of function 'TBackgroundWorkers.WaitAndRetryForever' might be undefined
[dcc32 Hint] Quick.Threads.pas(603): H2219 Private symbol 'fMaxRetries' declared but never used

**Comment by exilon** [comment] 2022-01-17 20:06
These warnings will be resolved in next commit.

**Comment by JWBokx** [comment] 2022-01-18 10:41
@exilon That's a good thing! Thankyou, I'll check for the new commit so now and then.

**Comment by exilon** [comment] 2022-01-20 17:18
Reported to embarcadero to update getit version.

**Comment by exilon** [comment] 2022-01-22 14:22
Getit version update confirmed.

**Comment by JWBokx** [comment] 2022-01-24 13:16
Had to push getit a bit before it shows the new version.
But I have it now, first build left a few new hints, but not in de parts we use.
`Building MultiLogger.dproj (Debug, Win64)
brcc32 command line for "MultiLogger.vrc"
  c:\program files (x86)\embarcadero\studio\21.0\bin\cgrc.exe -c65001 MultiLogger.vrc -foMultiLogger.res 
dcc64 command line for "MultiLogger.dpr"
  c:\program files (x86)\embarcadero\studio\21.0\bin\dcc64.exe -$O- -$W+ --no-config -B -Q -TX.exe -AGenerics.Collections=System.Generics.Collections;
  Generics.Defaults=System.Generics.Defaults;WinTypes=Winapi.Windows;WinProcs=Winapi.Windows;DbiTypes=BDE;DbiProcs=BDE;DbiErrs=BDE -DDEBUG 
  -E.\bin\Win64\Debug -I"c:\program files (x86)\embarcadero\studio\21.0\lib\Win64\debug";"c:\program files 
  (x86)\embarcadero\studio\21.0\lib\Win64\release";D:\Documenten\Embarcadero\Studio\21.0\Imports;"c:\program files 
  (x86)\embarcadero\studio\21.0\Imports";C:\Users\Public\Documents\Embarcadero\Studio\21.0\Dcp\Win64;"c:\program files 
  (x86)\embarcadero\studio\21.0\include";"C:\Program Files (x86)\FastReports\LibD27x64";
  C:\Users\Public\Documents\Embarcadero\Studio\21.0\CatalogRepository\KonopkaControls-270-6.2.3\Lib\RX10.4\Win64;
  D:\Documenten\Embarcadero\Studio\21.0\CatalogRepository\JEDICodeLibraryJCL-3.4\lib\d27\win64;
  D:\Documenten\Embarcadero\Studio\21.0\CatalogRepository\JEDICodeLibraryJCL-3.4\source\include;
  D:\Documenten\Embarcadero\Studio\21.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.9\lib\D27\win64;
  D:\Documenten\Embarcadero\Studio\21.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.9\common;
  D:\Documenten\Embarcadero\Studio\21.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.9\Resources;"C:\Program Files (x86)\Add-in Express\Add-in 
  Express for VCL\Packages\Delphi10.4\Win64";D:\Source\Delphi\ZeosLib\packages\DelphiXE10.4\Win64\Debug;
  D:\Source\Delphi\DevExpress_20_2_4_D10.4\VCL\Library\RS27\Win64;"C:\Program Files (x86)\Devart\MyDAC for RAD Studio 10.4\Lib\Win64";"C:\Program Files 
  (x86)\Devart\MyDAC for RAD Studio 10.4\Bin\Win64";"C:\Program Files (x86)\SiComponents\TsiLang\Units\ERS XE104\Win64";"C:\Program Files 
  (x86)\SiComponents\TsiLang\Units";"C:\Program Files (x86)\SiComponents\TsiLang\Units\Auxilary";
  D:\Documenten\Embarcadero\Studio\21.0\CatalogRepository\DECLite-6.2.1\Source;D:\Documenten\Embarcadero\Studio\21.0\CatalogRepository\QuickLib-2.3.1;
  D:\Documenten\Embarcadero\Studio\21.0\CatalogRepository\QuickLogger-1.46 -LEC:\Users\Public\Documents\Embarcadero\Studio\21.0\Bpl\Win64 
  -LNC:\Users\Public\Documents\Embarcadero\Studio\21.0\Dcp\Win64 -NU.\bin\Win64\Debug\dcu -NSWinapi;System.Win;Data.Win;Datasnap.Win;Web.Win;Soap.Win;
  Xml.Win;System;Xml;Data;Datasnap;Web;Soap; -O"c:\program files (x86)\embarcadero\studio\21.0\lib\Win64\release";
  D:\Documenten\Embarcadero\Studio\21.0\Imports;"c:\program files (x86)\embarcadero\studio\21.0\Imports";
  C:\Users\Public\Documents\Embarcadero\Studio\21.0\Dcp\Win64;"c:\program files (x86)\embarcadero\studio\21.0\include";"C:\Program Files 
  (x86)\FastReports\LibD27x64";C:\Users\Public\Documents\Embarcadero\Studio\21.0\CatalogRepository\KonopkaControls-270-6.2.3\Lib\RX10.4\Win64;
  D:\Documenten\Embarcadero\Studio\21.0\CatalogRepository\JEDICodeLibraryJCL-3.4\lib\d27\win64;
  D:\Documenten\Embarcadero\Studio\21.0\CatalogRepository\JEDICodeLibraryJCL-3.4\source\include;
  D:\Documenten\Embarcadero\Studio\21.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.9\lib\D27\win64;
  D:\Documenten\Embarcadero\Studio\21.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.9\common;
  D:\Documenten\Embarcadero\Studio\21.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.9\Resources;"C:\Program Files (x86)\Add-in Express\Add-in 
  Express for VCL\Packages\Delphi10.4\Win64";D:\Source\Delphi\ZeosLib\packages\DelphiXE10.4\Win64\Debug;
  D:\Source\Delphi\DevExpress_20_2_4_D10.4\VCL\Library\RS27\Win64;"C:\Program Files (x86)\Devart\MyDAC for RAD Studio 10.4\Lib\Win64";"C:\Program Files 
  (x86)\Devart\MyDAC for RAD Studio 10.4\Bin\Win64";"C:\Program Files (x86)\SiComponents\TsiLang\Units\ERS XE104\Win64";"C:\Program Files 
  (x86)\SiComponents\TsiLang\Units";"C:\Program Files (x86)\SiComponents\TsiLang\Units\Auxilary";
  D:\Documenten\Embarcadero\Studio\21.0\CatalogRepository\DECLite-6.2.1\Source;D:\Documenten\Embarcadero\Studio\21.0\CatalogRepository\QuickLib-2.3.1;
  D:\Documenten\Embarcadero\Studio\21.0\CatalogRepository\QuickLogger-1.46 -R"c:\program files (x86)\embarcadero\studio\21.0\lib\Win64\release";
  D:\Documenten\Embarcadero\Studio\21.0\Imports;"c:\program files (x86)\embarcadero\studio\21.0\Imports";
  C:\Users\Public\Documents\Embarcadero\Studio\21.0\Dcp\Win64;"c:\program files (x86)\embarcadero\studio\21.0\include";"C:\Program Files 
  (x86)\FastReports\LibD27x64";C:\Users\Public\Documents\Embarcadero\Studio\21.0\CatalogRepository\KonopkaControls-270-6.2.3\Lib\RX10.4\Win64;
  D:\Documenten\Embarcadero\Studio\21.0\CatalogRepository\JEDICodeLibraryJCL-3.4\lib\d27\win64;
  D:\Documenten\Embarcadero\Studio\21.0\CatalogRepository\JEDICodeLibraryJCL-3.4\source\include;
  D:\Documenten\Embarcadero\Studio\21.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.9\lib\D27\win64;
  D:\Documenten\Embarcadero\Studio\21.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.9\common;
  D:\Documenten\Embarcadero\Studio\21.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.9\Resources;"C:\Program Files (x86)\Add-in Express\Add-in 
  Express for VCL\Packages\Delphi10.4\Win64";D:\Source\Delphi\ZeosLib\packages\DelphiXE10.4\Win64\Debug;
  D:\Source\Delphi\DevExpress_20_2_4_D10.4\VCL\Library\RS27\Win64;"C:\Program Files (x86)\Devart\MyDAC for RAD Studio 10.4\Lib\Win64";"C:\Program Files 
  (x86)\Devart\MyDAC for RAD Studio 10.4\Bin\Win64";"C:\Program Files (x86)\SiComponents\TsiLang\Units\ERS XE104\Win64";"C:\Program Files 
  (x86)\SiComponents\TsiLang\Units";"C:\Program Files (x86)\SiComponents\TsiLang\Units\Auxilary";
  D:\Documenten\Embarcadero\Studio\21.0\CatalogRepository\DECLite-6.2.1\Source;D:\Documenten\Embarcadero\Studio\21.0\CatalogRepository\QuickLib-2.3.1;
  D:\Documenten\Embarcadero\Studio\21.0\CatalogRepository\QuickLogger-1.46 -U"c:\program files (x86)\embarcadero\studio\21.0\lib\Win64\debug";
  "c:\program files (x86)\embarcadero\studio\21.0\lib\Win64\release";D:\Documenten\Embarcadero\Studio\21.0\Imports;"c:\program files 
  (x86)\embarcadero\studio\21.0\Imports";C:\Users\Public\Documents\Embarcadero\Studio\21.0\Dcp\Win64;"c:\program files 
  (x86)\embarcadero\studio\21.0\include";"C:\Program Files (x86)\FastReports\LibD27x64";
  C:\Users\Public\Documents\Embarcadero\Studio\21.0\CatalogRepository\KonopkaControls-270-6.2.3\Lib\RX10.4\Win64;
  D:\Documenten\Embarcadero\Studio\21.0\CatalogRepository\JEDICodeLibraryJCL-3.4\lib\d27\win64;
  D:\Documenten\Embarcadero\Studio\21.0\CatalogRepository\JEDICodeLibraryJCL-3.4\source\include;
  D:\Documenten\Embarcadero\Studio\21.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.9\lib\D27\win64;
  D:\Documenten\Embarcadero\Studio\21.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.9\common;
  D:\Documenten\Embarcadero\Studio\21.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.9\Resources;"C:\Program Files (x86)\Add-in Express\Add-in 
  Express for VCL\Packages\Delphi10.4\Win64";D:\Source\Delphi\ZeosLib\packages\DelphiXE10.4\Win64\Debug;
  D:\Source\Delphi\DevExpress_20_2_4_D10.4\VCL\Library\RS27\Win64;"C:\Program Files (x86)\Devart\MyDAC for RAD Studio 10.4\Lib\Win64";"C:\Program Files 
  (x86)\Devart\MyDAC for RAD Studio 10.4\Bin\Win64";"C:\Program Files (x86)\SiComponents\TsiLang\Units\ERS XE104\Win64";"C:\Program Files 
  (x86)\SiComponents\TsiLang\Units";"C:\Program Files (x86)\SiComponents\TsiLang\Units\Auxilary";
  D:\Documenten\Embarcadero\Studio\21.0\CatalogRepository\DECLite-6.2.1\Source;D:\Documenten\Embarcadero\Studio\21.0\CatalogRepository\QuickLib-2.3.1;
  D:\Documenten\Embarcadero\Studio\21.0\CatalogRepository\QuickLogger-1.46 -CC -V -VN -VR 
  -NBC:\Users\Public\Documents\Embarcadero\Studio\21.0\Dcp\Win64 -NHC:\Users\Public\Documents\Embarcadero\Studio\21.0\hpp\Win64 
  -NO.\bin\Win64\Debug\dcu  MultiLogger.dpr   
[dcc64 Hint] Quick.Logger.Provider.Redis.pas(60): H2219 Private symbol 'RedisLPUSH' declared but never used
[dcc64 Hint] Quick.Logger.Provider.Redis.pas(63): H2219 Private symbol 'RedisPING' declared but never used
[dcc64 Hint] Quick.Logger.Provider.Telegram.pas(105): H2443 Inline function 'TJSONAncestor.ToJSON' has not been expanded because unit 'System.JSON' is not specified in USES list
[dcc64 Warning] Quick.Logger.Provider.Twilio.pas(147): W1000 Symbol 'URLEncode' is deprecated: 'Use TNetEncoding.URL.Encode'
[dcc64 Warning] Quick.Logger.Provider.Twilio.pas(147): W1000 Symbol 'URLEncode' is deprecated: 'Use TNetEncoding.URL.Encode'
[dcc64 Warning] Quick.Logger.Provider.Twilio.pas(148): W1000 Symbol 'URLEncode' is deprecated: 'Use TNetEncoding.URL.Encode'
[dcc64 Warning] Quick.Logger.Provider.Twilio.pas(148): W1000 Symbol 'URLEncode' is deprecated: 'Use TNetEncoding.URL.Encode'
[dcc64 Warning] Quick.Logger.Provider.Twilio.pas(149): W1000 Symbol 'URLEncode' is deprecated: 'Use TNetEncoding.URL.Encode'
[dcc64 Warning] Quick.Logger.Provider.Twilio.pas(149): W1000 Symbol 'URLEncode' is deprecated: 'Use TNetEncoding.URL.Encode'
Success
Elapsed time: 00:00:02.2`

**Comment by exilon** [comment] 2022-01-24 18:27
These warnings are from QuickLib library. You need to update QuickLib from GetIt to get rid of them.

**Comment by exilon** [comment] 2022-01-24 20:17
Umm, Seems like embarcadero is not getting correct version from github. These warnings were removed in last commits, but i see files outdated.

**Comment by exilon** [comment] 2022-01-24 21:28
I've reported to embarcadero. I'm waiting for a response.

**Comment by exilon** [comment] 2022-01-26 20:44
GetIt version is correct now.

**Closed** 2022-06-08 20:22 UTC
